apiVersion: v1
kind: Secret
metadata:
  name: tourdevino-secrets
  namespace: tourdevino
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: tourdevino
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/tourdevino?schema=public
  SHADOW_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/tourdevino_shadow?schema=public
  JWT_ACCESS_SECRET: change_me_access
  JWT_REFRESH_SECRET: change_me_refresh
  STRIPE_WEBHOOK_SECRET: change_me_webhook
